### ISSUE TITLE
is it supposed to work with Windows 10 ?

### ISSUE THREAD

**Issue by Aymkdn** [OrangeSec/CortanaProxy#4]
Hi,

I tried to make it work on Windows 10 (desktop), but it doesn't seem to work, and in the console I don't have any error. I tried to debug adding some `console.log` into `proxy.js` but no success either (looks like the request don't go thru the proxy).

Did you try? Is there something else special to do?

Thanks

**Comment by ghost** [comment]
The readme specifies that this is meant for windows phone 8.1, so no it's not supported by windows 10.

I would love to see the functionality though, I'll look into it as I would love to be able to write say ruby extensions for custom commands and responses.

**Comment by Aymkdn** [comment]
OK thanks for the reply.
